<?php if ($this->posts) : ?>
    <?php foreach ($this->posts as $post) : ?>
    <div id="post_<?= $post->id ?>">
        <h2><?= $post->title ?></h2>
        <div class="content">
        <?= $post->content ?>
        </div>
    </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($this->user) : ?>
    You are logged in as <strong><?= $this->user->getEmail() ?></strong> (<a href="/user/logout">logout</a>)
<?php else: ?>
    You can login <a href="/user/login">here</a>
<?php endif; ?>
